In [30]:
import numpy as np
with open('day9_input.txt', 'r') as f:
    lines = f.read().splitlines()
    l = [[10] + [int(num) for num in l] +[10] for l in lines]
l = np.array([[10]*len(l[0])] + l + [[10]*len(l[0])])
print(l)

[[10 10 10 ... 10 10 10]
 [10  9  8 ...  6  7 10]
 [10  5  9 ...  5  6 10]
 ...
 [10  5  3 ...  9  5 10]
 [10  6  2 ...  3  4 10]
 [10 10 10 ... 10 10 10]]


In [37]:
risk_lvls = []
for i in range(1, len(l)-1):
    for j in range(1, len(l[0])-1):
        if((l[i,j] < l[i-1,j]) and (l[i,j] < l[i+1,j]) and (l[i,j] < (l[i, j-1]) and l[i,j] < l[i,j+1])):
            risk_lvls.append(l[i,j] + 1)
print(risk_lvls)
print(sum(risk_lvls))

[1, 5, 1, 4, 6, 5, 5, 2, 1, 1, 1, 3, 3, 2, 2, 7, 3, 1, 1, 5, 6, 1, 2, 3, 4, 2, 2, 1, 6, 1, 5, 1, 1, 1, 2, 1, 1, 4, 1, 1, 4, 2, 4, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 3, 6, 3, 1, 4, 1, 1, 4, 2, 1, 3, 1, 4, 4, 1, 4, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 3, 2, 4, 1, 1, 3, 2, 4, 2, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 2, 1, 3, 2, 3, 3, 2, 1, 2, 3, 2, 3, 2, 1, 5, 2, 1, 5, 2, 1, 2, 4, 2, 4, 4, 1, 1, 1, 2, 1, 5, 1, 6, 3, 1, 5, 4, 1, 1, 2, 1, 2, 1, 2, 3, 1, 2, 2, 4, 1, 2, 1, 1, 2, 1, 1, 4, 2, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 2, 2, 1, 2, 2, 1, 4, 1, 6, 2, 6, 5, 2, 5, 3, 1, 1, 1, 1, 2, 4, 1, 5, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 3, 6, 2, 5, 3, 1, 4, 1, 2, 2, 5, 1, 1, 1, 4]
486


102